### ISSUE TITLE
The Escapists

### ISSUE THREAD

**Issue by TheCheluis** [Rinnegatamante/Android2Vita-Candidate-Ports-List#107]
Name: The Escapists: Prison Escape
Version: 1.1.5.556924
Google Play Link: https://play.google.com/store/apps/details?id=com.team17.escapists
Amazon App Store Link: https://www.amazon.com/-/de/dp/B072F7Y8TD/ref=sr_1_4?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&dchild=1&keywords=The+Escapists&qid=1630600418&sr=8-4
Download link: //

Comments:

Has ARMv7 Build: Yes
Has ARMv6 Build: No
GLES Version: 2
Online Features: No

**Comment by Girotin** [comment]
Why this one got closed? It's small game in general, Unity engine support is the problem?
