### ISSUE TITLE
Batman The Dark Knight Rises by Gameloft

### ISSUE THREAD

**Issue by adanmiguel** [Rinnegatamante/Android2Vita-Candidate-Ports-List#111]
Name:Batman The Dark Knight Rises
Version:   1.1.6 
Google Play Link: https://www.playstoresales.com/app/com-gameloft-android-anmp-gloftkrhmhlen/

Has ARMv7 Build:
GLES version:
Online Features:

**Comment by Calistex** [comment]
Already posted
