### ISSUE TITLE
RollerCoaster Tycoon Classic

### ISSUE THREAD

**Issue by Invictaz** [Rinnegatamante/Android2Vita-Candidate-Ports-List#116]
Name: RollerCoaster Tycoon Classic
Version: 1.0.0.1903060
Google Play Link: https://play.google.com/store/apps/details?id=com.atari.mobile.rctclassic

Has ARMv7 Build: Yes
GLES version: Unknown
Online Features: Unknown

**Comment by Rinnegatamante** [comment]
https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/11
