### ISSUE TITLE
Star Wars: KOTOR II

### ISSUE THREAD

**Issue by ImSirJ** [Rinnegatamante/Android2Vita-Candidate-Ports-List#126]
Name: Star Wars: KOTOR II
Version: 2.0.1
Google Play Link: https://play.google.com/store/apps/details?id=com.aspyr.swkotorii&hl=es&gl=US

Has ARMv7 Build: Not sure
GLES version: Not sure
Online Features: No

**Comment by Rinnegatamante** [comment]
Duplicate.
