### ISSUE TITLE
Dead Trigger 1

### ISSUE THREAD

**Issue by CodeMasterh** [Rinnegatamante/Android2Vita-Candidate-Ports-List#129]
Name: Dead Trigger
Version: 1.5.0
Google Play Link: https://play.google.com/store/apps/details?id=com.madfingergames.deadtrigger&hl=pt_BR&gl=US

Has ARMv7 Build: Yes
GLES version:
Online Features: NO

**Comment by Idah00** [comment]
Request already exists here: https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/122

**Comment by Idah00** [comment]
Request already exists here: #122
