### ISSUE TITLE
Almora Darkosen RPG

### ISSUE THREAD

**Issue by Idah00** [Rinnegatamante/Android2Vita-Candidate-Ports-List#204]
Name: Almora Darkosen RPG
Version: 1.0.82
Google Play Link: https://play.google.com/store/apps/details?id=com.GearStudio.AlmoraDarkosen&hl=de&gl=US
Amazon App Store Link: //
Download link: //

Comments:
- Information gathered by JensB.

Has ARMv7 Build: Yes
Has ARMv6 Build: No
GLES Version: 2
Online Features: //

**Comment by Rinnegatamante** [comment]
GMS game, refer to YoYo Loader.
