### ISSUE TITLE
GRIS

### ISSUE THREAD

**Issue by ghost** [Rinnegatamante/Android2Vita-Candidate-Ports-List#21]
Name: GRIS
Version: 1.0.2
Google Play Link: https://play.google.com/store/apps/details?id=com.devolver.grispaid

Has ARMv7 Build: Not Sure
GLES version: Not Sure
Online Features: No

**Comment by Rinnegatamante** [comment]
GRIS is armv8 only. Not possible.

**Comment by Idah00** [comment]
It's also armv7 according to m1s3ry.

**Comment by Idah00** [comment]
But it is gles3 according to shift otherworldly.
