### ISSUE TITLE
Steven Universe - Attack the Light

### ISSUE THREAD

**Issue by BravestW** [Rinnegatamante/Android2Vita-Candidate-Ports-List#215]
Name: Attack the Light
Version:  1.3.5
Google Play Link: https://play.google.com/store/apps/details?id=com.turner.stevenrpg&hl=en_US&gl=US 
Amazon App Store Link: https://www.amazon.com/gp/aw/d/B00V3WBHBU/ref=cm_cr_arp_mb_bdcrb_top?ie=UTF8 
Download link: https://apk-top.net/en/1054-attack-the-light.html 

Comments:

Has ARMv7 Build: Yes
Has ARMv6 Build: No
GLES version: 3.1
Online Features: //

**Comment by Wumaoist** [comment]
Not Possible, because of GLES version: 3
