### ISSUE TITLE
Re-Volt Classic

### ISSUE THREAD

**Issue by once13one** [Rinnegatamante/Android2Vita-Candidate-Ports-List#22]
Name: Re-Volt Classic (Premium)
Version: 1.3.0
Google Play Link:
No link, game been deleted from GP

Has ARMv7 Build: Yes
GLES version: ?
Online Features: No (Not Sure)

**Comment by once13one** [comment]
Maybe double:
https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/20

but, other version

**Comment by Idah00** [comment]
RVGL is a community improved version of Re-Volt Classic the company behind it were douches who used and distributed community patches without asking and giving credits...

**Comment by once13one** [comment]
> RVGL is a community improved recreation of Re-Volt Classic the company behind it were douches who used and distributed community patches without asking and giving credits...

ok, then I close this issue.
