### ISSUE TITLE
Mental Hospital: Eastern Bloc

### ISSUE THREAD

**Issue by octaviojss** [Rinnegatamante/Android2Vita-Candidate-Ports-List#220]
Name: Mental Hospital: Eastern Bloc
Version: 2.05.99
Google Play Link: https://play.google.com/store/apps/details?id=com.agaming.hospital&hl=pt_PT&gl=US
Amazon App Store Link: 
Download link: https://www.todoaquibyalex.com/2017/01/mental-hospital-eastern-bloc.html

Comments:

Has ARMv7 Build: 
Has ARMv6 Build:
GLES Version:
Online Features: no

**Comment by Wumaoist** [comment]
Has ARMv7 Build: Yes
Has ARMv6 Build: //
GLES Version: 2.0
Online Features: no
