### ISSUE TITLE
Apollo Justice: Ace Attorney

### ISSUE THREAD

**Issue by JKammder27** [Rinnegatamante/Android2Vita-Candidate-Ports-List#236]
Name: Apollo Justice: Ace Attorney
Version: 1.00.02
Google Play Link: https://play.google.com/store/apps/details?id=jp.co.capcom.gyakusai4en
Amazon App Store Link: //
Download link: //

Comments:

Has ARMv7 Build: //
Has ARMv6 Build: //
GLES Version: //
Online Features: In-app payments.

**Comment by Thetouchedjoe** [comment]
yeah this issue is closed cuz this game has libunity.so
