### ISSUE TITLE
Ace Attorney: Spirit of Justice

### ISSUE THREAD

**Issue by JKammder27** [Rinnegatamante/Android2Vita-Candidate-Ports-List#237]
Name: Ace Attorney: Spirit of Justice
Version: 1.00.01
Google Play Link: https://play.google.com/store/apps/details?id=jp.co.capcom.gyakusai6en
Amazon App Store Link: //
Download link: //

Comments:

Has ARMv7 Build: //
Has ARMv6 Build: //
GLES Version: //
Online Features: Game has DRM and cannot be played offline.

**Comment by Thetouchedjoe** [comment]
closed cause cant determined the openGL version
