### ISSUE TITLE
The World Ends With You: Solo Remix

### ISSUE THREAD

**Issue by JKammder27** [Rinnegatamante/Android2Vita-Candidate-Ports-List#240]
Name: The World Ends With You: Solo Remix
Version: 1.0.4
Google Play Link: https://play.google.com/store/apps/details?id=com.square_enix.android_googleplay.subarashikikonosekai_solo
Amazon App Store Link: //
Download link: //

Comments:

Has ARMv7 Build: //
Has ARMv6 Build: //
GLES Version: //
Online Features: In-app purchases and trading

**Comment by Earleybyrd** [comment]
There’s a bounty out for this game, it should be given the bounty label 💯
