### ISSUE TITLE
Forgotten Memories

### ISSUE THREAD

**Issue by galdin1** [Rinnegatamante/Android2Vita-Candidate-Ports-List#29]
Name: Forgotten Memories
Version: 1.0.8
Google Play Link: https://play.google.com/store/apps/details?id=com.psychoseinteractive.forgottenmemories

Has ARMv7 Build: yes
GLES version: 3
Online Features: no

Classic survival horror. Developers wanna release it on vita but canceled this port, maybe they already can give you source code to port this on vita.

**Comment by CatoTheYounger97** [comment]
unity
