### ISSUE TITLE
Dan The Man

### ISSUE THREAD

**Issue by BravestW** [Rinnegatamante/Android2Vita-Candidate-Ports-List#315]
Name: Dan The Man
Version: 1.10.31
Google Play Link: https://play.google.com/store/apps/details?id=com.halfbrick.dantheman&hl=en_US&gl=US 
Amazon App Store Link: https://www.amazon.com/gp/aw/d/B01LWMXIB1/ref=cm_cr_arp_mb_bdcrb_top?ie=UTF8 
Download link:

Comments: Has in-app purchases

Has ARMv7 Build: ?
Has ARMv6 Build: ?
GLES Version: ?
Online Features: Has multiplayer, in-app purchases and ads.

**Comment by Wumaoist** [comment]
Name: Dan The Man
Version: //
Google Play Link: https://play.google.com/store/apps/details?id=com.halfbrick.dantheman&hl=en_US&gl=US
Amazon App Store Link: https://www.amazon.com/gp/aw/d/B01LWMXIB1/ref=cm_cr_arp_mb_bdcrb_top?ie=UTF8
Download link:

Comments: 

Has ARMv7 Build:  Yes
Has ARMv6 Build: //
GLES Version: 2.0
Online Features: in-app purchases and ads.
