### ISSUE TITLE
Genshin Impact

### ISSUE THREAD

**Issue by animekai** [Rinnegatamante/Android2Vita-Candidate-Ports-List#37]
Name: Genshin Impact
Version: 1.3
Google Play Link:https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact

Has ARMv7 Build: not sure
GLES version: 3
Online Features: yes

**Comment by Rinnegatamante** [comment]
Kotlin, definitely impossible

**Comment by Idah00** [comment]
The absolute madman
