### ISSUE TITLE
[Pocket God]

### ISSUE THREAD

**Issue by LuanTeles** [Rinnegatamante/Android2Vita-Candidate-Ports-List#372]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity Games

- [X] This game is not made in Unity and does not contain a libunity.so

### No Java Games

- [X] This game is not made in Java and does not contain a libgdx.so

### Game Name

Pocket God

### Game Version

1.40.2

### ARM Build Version

ARMv6

### OpenGL Version

GLES 1

### FMOD Usage

No FMOD

### Listed or Delisted

Amazon App Store

### Store Link

https://www.amazon.com.br/Bolt-Creative-Pocket-God/dp/B00AVXG3CU

**Comment by CatoTheYounger97** [comment]
no lib folder, please read instructions.
