### ISSUE TITLE
Evil Nun: Horror School

### ISSUE THREAD

**Issue by Apfelsaft147** [Rinnegatamante/Android2Vita-Candidate-Ports-List#379]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity Games

- [X] This game is not made in Unity and does not contain a libunity.so

### No Java Games

- [X] This game is not made in Java and does not contain a libgdx.so

### Game Name

Evil Nun

### Game Version

1.8.6

### ARM Build Version

ARMv6

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.keplerians.evilnun

**Comment by Rinnegatamante** [comment]
This game is Unity, consider yourself banned from writing Issues on any of my repositories.
