### ISSUE TITLE
AlephOne Android

### ISSUE THREAD

**Issue by Dorr8** [Rinnegatamante/Android2Vita-Candidate-Ports-List#382]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Aleph One Trilogy

### Game Version

v0.3.0-alpha

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

### Store Link

https://github.com/daniele-rapagnani/alephone-android/releases/tag/v0.3.0-alpha

### Comment Box

It is on git, but I just selected Delisted since there isn't an "other" option or something along those lines.

**Comment by CatoTheYounger97** [comment]
recorded elsewhere
