### ISSUE TITLE
DroidArcadia

### ISSUE THREAD

**Issue by Dorr8** [Rinnegatamante/Android2Vita-Candidate-Ports-List#392]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

DroidArcadia

### Game Version

1.5

### ARM Build Version

ARMv7

### OpenGL Version

GLES 1

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

### Store Link

http://amigan.1emu.net/releases/

### Comment Box

An Android version of WinArcadia that was made recently. I couldn't find anything related to OpenGLES, so I went with the default selection. Disregard the OpenGL Version.

**Comment by CatoTheYounger97** [comment]
Can't fine enough information to fit port citeria
