### ISSUE TITLE
Subway surfers 

### ISSUE THREAD

**Issue by RONIN0095** [Rinnegatamante/Android2Vita-Candidate-Ports-List#397]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Subway surfers 

### Game Version

2.60

### ARM Build Version

ARMv6

### OpenGL Version

GLES 1

### FMOD Usage

libfmod.so

### Listed or Delisted

Google Play Store

### Store Link

https://play-google-com.translate.goog/store/apps/details?id=com.kiloo.subwaysurf&_x_tr_sl=auto&_x_tr_tl=de&_x_tr_hl=de-DE

**Comment by CatoTheYounger97** [comment]
game is unity, please read instructions
