### ISSUE TITLE
Sonic 4 - Episode I

### ISSUE THREAD

**Issue by JaviLopg24** [Rinnegatamante/Android2Vita-Candidate-Ports-List#406]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Sonic 4 - Episode I

### Game Version

1.5.0

### ARM Build Version

ARMv6

### OpenGL Version

GLES 1

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.sega.sonic4epi

**Comment by CatoTheYounger97** [comment]
closed as gles version cannot be determined.
