### ISSUE TITLE
Planescape: Torment: Enhanced

### ISSUE THREAD

**Issue by Arka161** [Rinnegatamante/Android2Vita-Candidate-Ports-List#414]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Planescape: Torment: Enhanced

### Game Version

3.1.3.0

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.beamdog.pstee&hl=en&gl=US

### Comment Box

This looks like it's using the same engine and SO configurations as Baldur's Gate: Enhanced Edition when analyzed using Ghidra.

**Comment by CatoTheYounger97** [comment]
https://github.com/Northfear/gemrb-vita
