### ISSUE TITLE
Neverwinter Nights: Enhanced Edition

### ISSUE THREAD

**Issue by Arka161** [Rinnegatamante/Android2Vita-Candidate-Ports-List#415]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Neverwinter Nights: Enhanced Edition

### Game Version

8193A00011b41

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.beamdog.nwnandroid&hl=en&gl=US

**Comment by CatoTheYounger97** [comment]
https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/362
