### ISSUE TITLE
Five Nights at Freddy's : Sister Location

### ISSUE THREAD

**Issue by treasboi** [Rinnegatamante/Android2Vita-Candidate-Ports-List#425]
### Submission Rules

- [x] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [x] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Five Nights at Freddy's : Sister Location

### Game Version

2.0.2

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.scottgames.sisterlocation&hl=en

### Comment Box

Fnaf SL is the fifth (if we count fnaf world its sixth) game of the fnaf franchise. The game is Point & Click based a horror game.

**Comment by treasboi** [comment]
NOTE : The 2.0.2 is remaster of the original game if vita could not handle that I reccomened using 1.2 version of the game

**Comment by treasboi** [comment]
Sorry everyone for misunderstanding but I searched up the game files again and sadly I found the game is made with Java,(it includes libgdx.so) from that reason I can't let this port to continue also Rinnegatamante,all fnaf games (1,2,3,4,SL,Fnaf WORLD,Fnaf Pizzeria Simulator,Fnaf UCN) are made with Java so they can't be ported to PSVita

**Comment by Zielakless** [comment]
> ❌ Java games (libgdx.so)
Meanwhile: **lib/armeabi-v7a/libgdx.so**

**Comment by Zielakless** [comment]
**If lib folder contains libgdx.so or libunity.so, the game CANNOT be ported.**

**Comment by Zielakless** [comment]
**If lib folder contains libgdx.so or libunity.so, the game CANNOT be ported.**

**Comment by Zielakless** [comment]
If lib folder contains **libgdx.so** or libunity.so, the game CANNOT be ported.
