### ISSUE TITLE
J2ME Loader Emulator 

### ISSUE THREAD

**Issue by Erken22** [Rinnegatamante/Android2Vita-Candidate-Ports-List#444]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

J2ME Loader

### Game Version

1.7.8

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=ru.playsoftware.j2meloader

**Comment by v-atamanenko** [comment]
it's java https://github.com/nikita36078/J2ME-Loader
