### ISSUE TITLE
Carnivores: Dinosaur Hunter HD

### ISSUE THREAD

**Issue by JavDVD123** [Rinnegatamante/Android2Vita-Candidate-Ports-List#447]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Carnivores: Dinosaur Hunter HD

### Game Version

1.6.7

### ARM Build Version

ARMv6

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.tatem.dinhunterhd

**Comment by v-atamanenko** [comment]
<img width="468" alt="Screenshot 2023-04-09 at 13 19 19" src="https://user-images.githubusercontent.com/11796486/230764922-94832f2d-57f4-40bf-9e62-8377193ea5f3.png">
this is a clear sign of a Java usage too heavy to deal with

**Comment by JavDVD123** [comment]
![2023_04_09_07 55 37](https://user-images.githubusercontent.com/128942563/230771210-dfc31b8a-56fa-497b-85d3-a05791836c6e.jpg)
Friend that folder does not appear for me
