### ISSUE TITLE
Play! : Playstation 2 Emulator

### ISSUE THREAD

**Issue by treasboi** [Rinnegatamante/Android2Vita-Candidate-Ports-List#449]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Play! : Playstation 2 Emulator

### Game Version

2.7.1.0.6

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.virtualapplications.play&hl=en_US

### Comment Box

an ps2 emulator for android why it can't be on vita?

**Comment by treasboi** [comment]
Well the screenshot was old so you can't see the left and right buttons but the current version has L1,R1,L2,R2,L3 & R3

**Comment by treasboi** [comment]
What I mean by screenshot is google play screenshots

**Comment by RinMaru** [comment]
your joking, right? you can hardly run n64 Dreamcast much less MGBA

**Comment by v-atamanenko** [comment]
We have Play! ported to Vita already. Not much point in that though.
https://gitlab.com/xerpi/play
