### ISSUE TITLE
DuckStation

### ISSUE THREAD

**Issue by aurpiroth** [Rinnegatamante/Android2Vita-Candidate-Ports-List#476]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

DuckStation

### Game Version

0.1-4582

### ARM Build Version

ARMv7

### OpenGL Version

GLES 1

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.github.stenzek.duckstation&hl=es_MX&gl=RU

### Comment Box

It is a PSX emulator.
I didn't find the GLES in AndroidManifest.xml and with Ghidra i found libOpenSLES.so
I don't know if it is possible but I consider tha it would be a good emulator.

**Comment by treasboi** [comment]
It would be impossible to port i think
no info about gles version
