### ISSUE TITLE
SuperTuxKart

### ISSUE THREAD

**Issue by RaspberryNeko** [Rinnegatamante/Android2Vita-Candidate-Ports-List#507]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

SuperTuxKart

### Game Version

1.4

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=org.supertuxkart.stk

### Comment Box

the game is open source, and is under GPL 
The code can be found here: https://github.com/supertuxkart/stk-code/tree/master

**Comment by CatoTheYounger97** [comment]
game has been further evaluated as gles3, so it is not possible.
