### ISSUE TITLE
Cataclysm BN

### ISSUE THREAD

**Issue by Mokime** [Rinnegatamante/Android2Vita-Candidate-Ports-List#512]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Cataclysm: Bright Nights

### Game Version

a9106f0

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted 

### Store Link

https://github.com/cataclysmbnteam/Cataclysm-BN

### Comment Box

All libs:

libSDL2.so

libSDL2_image.so

libSDL2_mixer.so

libSDL2_ttf.so

libc++_shared.so

libhidapi.so

libmain.so

libmpg123.so

**Comment by CatoTheYounger97** [comment]
This isn't the right place for this submission. It has been recorded elsewhere.

**Comment by Mokime** [comment]
i understand. i just thought it could be done because of this.

https://github.com/cataclysmbnteam/Cataclysm-BN#contribute

**Comment by Mokime** [comment]
> This isn't the right place for this submission. It has been recorded elsewhere.

i understand. i just thought it could be done because of this.

https://github.com/cataclysmbnteam/Cataclys

**Comment by Mokime** [comment]
https://github.com/cataclysmbnteam/Cataclysm-BN#contribute
