### ISSUE TITLE
Survivalcraft 2

### ISSUE THREAD

**Issue by JGGamingOficial** [Rinnegatamante/Android2Vita-Candidate-Ports-List#514]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Survivalcraft 2

### Game Version

2.1.14.0

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.candyrufusgames.survivalcraft2&hl=pt_BR&gl=US

### Comment Box

3d sandbox game. It contains libmonodroid.so and libmonosgen-2.0.so. A great game to pass the time and have fun. (The game has gamepad support, the game has great gamepad support.)

**Comment by CatoTheYounger97** [comment]
game is not armv7 or lesser.
