### ISSUE TITLE
Digital Tamers: ReBorn

### ISSUE THREAD

**Issue by AnalogMan151** [Rinnegatamante/Android2Vita-Candidate-Ports-List#534]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Digital Tamers: Reborn

### Game Version

2.2.2

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

### Store Link

https://dragonrod342.itch.io/digital-tamers-reborn

### Comment Box

Free itch.io fan-made android game. Touch only inputs. Created with GameMaker.

**Comment by CatoTheYounger97** [comment]
https://github.com/Rinnegatamante/yoyoloader_vita 
The game is made in GameMaker Studio. Try it with yoyoloader for vita.
