### ISSUE TITLE
Age Of History 2

### ISSUE THREAD

**Issue by Satoyuo** [Rinnegatamante/Android2Vita-Candidate-Ports-List#599]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Age Of History 2

### Game Version

1.01584

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

libfmod.so, libfmodstudio.so

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=age.of.civilizations2.jakowski.lukasz&hl=es_PY

### Comment Box

Age of History II is a grand strategy war game that is simple to learn but hard to master, Your goal is to use military tactics and cunning diplomacy to unify the world or conquer it

**Comment by treasniko2** [comment]
I'ts not possible,game runs on java so i recommend you to read submission rules also back in the day someone already wanted the [port of aoh2](https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/268) but they refused their idea
