### ISSUE TITLE
60 Seconds! Atomic Adventure

### ISSUE THREAD

**Issue by ElViejoGaming** [Rinnegatamante/Android2Vita-Candidate-Ports-List#60]
Name:60 Seconds! Atomic Adventure
Version: 1.3.121
Google Play Link: https://play.google.com/store/apps/details?id=com.robotgentleman.game60seconds

Has ARMv7 Build: Not sure
GLES version: Not sure
Online Features: No

**Comment by HELLOcommaWORLD** [comment]
Has ARMv7 Build: Yes
GLES version: GLES2
