### ISSUE TITLE
Marble Blast Ultra

### ISSUE THREAD

**Issue by MysticAx0lotl** [Rinnegatamante/Android2Vita-Candidate-Ports-List#605]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Marble Blast Ultra

### Game Version

1.0

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

### Store Link

https://github.com/RandomityGuy/MBHaxe

### Comment Box

A Haxe rewrite of Marble Blast, it supports Marble Blast Gold, Ultra, and Platinum, but I specifically mentioned Ultra because it's my favorite. I couldn't figure out what openGL version it uses, but it does use SDL2. Due to the nature of Haxe, it could be natively ported, but one would have to use regular C since the libraries MBHaxe uses don't support anything other than C or JS. Therefore using the SO loader may be easier.

**Comment by CatoTheYounger97** [comment]
gles3
