### ISSUE TITLE
Terraria

### ISSUE THREAD

**Issue by Jaycawn** [Rinnegatamante/Android2Vita-Candidate-Ports-List#611]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Terraria

### Game Version

1.2.12785

### ARM Build Version

ARMv6

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=com.and.games505.TerrariaPaid&hl=en_US&gl=US

### Comment Box

Although Terraria already has it's own port on the PS Vita, the Android port has some exclusive content like 2 new bosses and a few seasonal events.

**Comment by Patrick2568** [comment]
Terraria is already on vita💀💀💀💀
