### ISSUE TITLE
Jet Set Radio 

### ISSUE THREAD

**Issue by Thetouchedjoe** [Rinnegatamante/Android2Vita-Candidate-Ports-List#615]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Jet Set Radio

### Game Version

1.07

### ARM Build Version

ARMv7

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

### Comment Box

libs for the JSR Vita :
- libjetsetradio.so
- libjsrcheckneon.so
- libjetsetradio-nn.so

the genre of the JSR is Sports and Action-adventure and also Simulation

**Comment by RinMaru** [comment]
why? this is already on Vita?

**Comment by Thetouchedjoe** [comment]
Oh ok
