### ISSUE TITLE
IdTech4A++

### ISSUE THREAD

**Issue by KlevezTemich** [Rinnegatamante/Android2Vita-Candidate-Ports-List#646]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

IdTech4A++

### Game Version

1.1.0harmattan37natasha

### ARM Build Version

ARMv7

### OpenGL Version

GLES 3+

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

### Store Link

https://f-droid.org/packages/com.karin.idTech4Amm/

### Comment Box

Unofficial port of the video games Quake 4, Prey 2006 and Doom 3

**Comment by CatoTheYounger97** [comment]
source port already investigated
