### ISSUE TITLE
Half Life 2 Tegra (Ep1,Ep2,Portal)

### ISSUE THREAD

**Issue by lunadigitalpro** [Rinnegatamante/Android2Vita-Candidate-Ports-List#66]
Name: Half Life 2
Version: unofficial android port for all devices (based on Tegra version)
Google Play Link: [https://play.google.com/store/apps/details?id=com.nvidia.valvesoftware.halflife2&hl=en&gl=US]

Has ARMv7 Build: Yes
GLES version: GLES 2.0 or OpenGL 2.0
Online Features: No

**Comment by DoradoOroOor** [comment]
It's already open

**Comment by once13one** [comment]
double:
https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/56

**Comment by lunadigitalpro** [comment]
Sorry, we must've been adding at the same time!

**Comment by once13one** [comment]
And now double x2:
https://github.com/Rinnegatamante/Android2Vita-Candidate-Ports-List/issues/33

use search in list
