### ISSUE TITLE
Among Us

### ISSUE THREAD

**Issue by DoradoOroOro** [Rinnegatamante/Android2Vita-Candidate-Ports-List#68]
Name: Among Us
Version: 2020.11.17
Google Play Link: https://play.google.com/store/apps/details?id=com.innersloth.spacemafia&hl=en&gl=US

Has ARMv7 Build: Yes
GLES version: Actually IDK
Online Features: Fully Multiplayer

**Comment by ElViejoGaming** [comment]
Maybe it's a bit difficult because of the multiplayer

**Comment by Rinnegatamante** [comment]
Online games are most likely virtually impossible to port since it would require to go through Google servers.

**Comment by ElViejoGaming** [comment]
De hecho,Y nadie tiene una central de miles de servidores

**Comment by DoradoOroOor** [comment]
Well, that's good to know, now there wont be more Among Us requests for Vita xD

**Comment by ElViejoGaming** [comment]
Sorry I forgot I don't speak English xd
and no other online game

**Comment by boyilka73** [comment]
Why not create a special firmware that will allow you to use Google services and other Internet services?
