### ISSUE TITLE
Call of Duty: Mobile

### ISSUE THREAD

**Issue by rtsage** [Rinnegatamante/Android2Vita-Candidate-Ports-List#69]
Name: Call of Duty: Mobile
Version: 1.0.19
Google Play Link: https://play.google.com/store/apps/details?id=com.activision.callofduty.shooter&hl=en&gl=US

Has ARMv7 Build: Most likely yes
GLES version: idk
Online Features: Yes

**Comment by once13one** [comment]
Only online. WTF?

**Comment by WildStriker101** [comment]
No multiplayer games!

**Comment by ElViejoGaming** [comment]
Impossible
