### ISSUE TITLE
Teeter

### ISSUE THREAD

**Issue by EGNL** [Rinnegatamante/Android2Vita-Candidate-Ports-List#803]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Teeter

### Game Version

1.21

### ARM Build Version

ARMv6

### OpenGL Version

GLES 2

### FMOD Usage

No FMOD

### Listed or Delisted

Delisted

### Comment Box

The nostalgic old game "Teeter" for old HTC phones. It contains "libcocos2dcpp.so" and also seems to have weird DRM that only causes it work on very old HTC phones. Because of this, I am not sure if it possible to port this game without it crashing.

**Comment by EGNL** [comment]
(Apparently the apk I found was one of the fake recreations of the game Teeter...)

**Comment by moyaimoment** [comment]
> (Apparently the apk I found was one of the fake recreations of the game Teeter...)

A remake or recreation could still be ported, it would be Teeter either way.

**Comment by EGNL** [comment]
The official Teeter has its own charm though. And a recreation would probably be better build from scratch for the Vita which this github page is not for.
