### ISSUE TITLE
Ace Attorney Trilogy

### ISSUE THREAD

**Issue by Poketubepoggu** [Rinnegatamante/Android2Vita-Candidate-Ports-List#811]
### Submission Rules

- [X] I have read the README.md and understand the submission rules

### No Unity or Java Games

- [X] This game is NOT made in Unity and does not contain a libunity.so
- [X] This game is NOT made in Java and does not contain a libgdx.so

### No Duplicate Submissions

- [X] This game is NOT already in the Android2Vita candidate port list

### Game Name

Ace Attorney Trilogy

### Game Version

1.00.02

### ARM Build Version

ARMv7

### OpenGL Version

GLES 1

### FMOD Usage

No FMOD

### Listed or Delisted

Google Play Store

### Store Link

https://play.google.com/store/apps/details?id=jp.co.capcom.gyakusai123

### Comment Box

I’m not sure about arm, fmod, or OpenGL version, you’ll have to recheck
If paid apps are not allowed, please remove

**Comment by SeaborneProto** [comment]
Checked the APK, it contains a libunity.so

There is probably a better way to port this game, like decomping it in unity.
