### ISSUE TITLE
Block Story Premium

### ISSUE THREAD

**Issue by rodrigoxmax** [Rinnegatamante/Android2Vita-Candidate-Ports-List#90]
Name: Block Story Premium
Version: 12.1.1
Google Play Link: https://play.google.com/store/apps/details?id=com.mindblocks.blocks&hl=en&gl=US

Has ARMv7 Build: Yes
GLES version: //
Online Features: //

**Comment by Idah00** [comment]
tested ti have GLES2 by shift otherworldly
