### ISSUE TITLE
Castle of illusion 

### ISSUE THREAD

**Issue by NoireCorp** [Rinnegatamante/Android2Vita-Candidate-Ports-List#92]
Name: Castle of illusion
![images-3](https://user-images.githubusercontent.com/78938736/107712422-5fea8a80-6c97-11eb-9b51-ba6b560fbc5d.jpeg)
![images-4](https://user-images.githubusercontent.com/78938736/107712845-164e6f80-6c98-11eb-8263-17123a59b67c.jpeg)
![images-5](https://user-images.githubusercontent.com/78938736/107712918-3847f200-6c98-11eb-974d-e0b7093467b8.jpeg)

Version: 1.4.2
Google Play Link: https://play.google.com/store/apps/details?id=com.disney.castleofillusion_goo

Has ARMv7 Build: ?
GLES version: ?
Online Features: Singleplayer ( No online)

**Comment by Mar2ck** [comment]
Duplicate #19
